[package]
name = "larptrix-desktop"
version = "0.4.0"
description = "Larptrix Linux desktop client"
authors = ["Larptrix"]
edition = "2021"
build = "build.rs"

[lib]
name = "larptrix_desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-notification = "2"
url = "2"

[workspace]
